### ISSUE TITLE
Firebase for Flutter instruction  for google-services version

### ISSUE THREAD

**Issue by zoechi** [flutter/website#2261]
@Dhana-Krishnasamy commented on [Thu Jan 24 2019](https://github.com/flutter/flutter/issues/26994)

The page https://codelabs.developers.google.com/codelabs/flutter-firebase/#6 suggests to use version 3.2.1 for com.google.gms:google-services, however with that version I get the below error 

 ```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzbq;
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzbq" on path: DexPathList[[zip file "/data/app/woopy.domain.com.woopy-KqNv1gE1ZomaesHCq33DJw==/base.apk"],nativeLibraryDirectories=[/data/app/woopy.domain.com.woopy-KqNv1gE1ZomaesHCq33DJw==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:2) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
```

However, the app works with version 4.2.0 ( this version is mentioned [here](https://firebase.google.com/docs/android/setup#manually_add_firebase) ) 

---

@zoechi commented on [Thu Jan 24 2019](https://github.com/flutter/flutter/issues/26994#issuecomment-457115722)

Please add the output of `flutter doctor -v`.

**Comment by Dhana-Krishnasamy** [comment]
here you go

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-GB)
    • Flutter version 1.0.0 at /Users/Dhana/Projects/flutter/sdk/flutter
    • Framework revision 5391447fae (8 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/Dhana/Library/Android/sdk
    • Android NDK at /Users/Dhana/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5556                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 8 Plus             • 8160CE5C-FA08-405E-A872-6749E8C5A653 • ios         • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
```

**Comment by ShivamSinghania** [comment]
Is it still recommended to use version 3.2.1 ?
I had a problem and using the latest version 4.3.3 resolved it.
Check https://github.com/FirebaseExtended/flutterfire/issues/1494 for more details.

**Comment by godslave05** [comment]
> Is it still recommended to use version 3.2.1 ?
> I had a problem and using the latest version 4.3.3 resolved it.
> Check [FirebaseExtended/flutterfire#1494](https://github.com/FirebaseExtended/flutterfire/issues/1494) for more details.

Same here, after updating to 1.12.13+hotfix.5 I fetched same issue and I need to update to 4.3.3 to resolve this

**Comment by sfshaza2** [comment]
@ditman, it looks like you've fixed this, yes?

https://codelabs.developers.google.com/codelabs/flutter-firebase/

**Comment by ditman** [comment]
@sfshaza2 I did! (I just didn't know this issue existed!) Apologies for not closing this before, and notifying people.

**Comment by sfshaza2** [comment]
Absolutely no problem! That explains why I couldn't find the old info in the source doc.  :D
