### ISSUE TITLE
flutter: 'package:flutter_doc/main.dart': error: Unexpected tag 0 (Nothing) in ?, expected a procedure, a

### ISSUE THREAD

**Issue by panda8z** [flutter/website#2560]
Page URL: https://flutter.dev/docs/development/ui/widgets-intro.html
Page source: https://github.com/flutter/website/tree/master/src/docs/development/ui/widgets-intro.md

Description of issue:

my Env:
```
$ flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (6 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

![image](https://user-images.githubusercontent.com/24646937/55283202-1b4df280-5390-11e9-9c00-692879cd3fe1.png)

The  Hello world  simple  code can not be Run correct.

Here is the error log Pic:
![image](https://user-images.githubusercontent.com/24646937/55283196-de81fb80-538f-11e9-97cc-a4acee069707.png)

and  here is error text

```bash
Initializing hot reload...                                             ⢿flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _CompileTimeError was thrown building MyApp(dirty):
flutter: 'package:flutter_doc/main.dart': error: Unexpected tag 0 (Nothing) in ?, expected a procedure, a
flutter: constructor or a function node
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
flutter: #1      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
flutter: #2      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
flutter: #10     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #11     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #12     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
        
Reloaded 1 of 432 libraries in 709ms.
```

**Comment by panda8z** [comment]
I  solve the problem just by   shutdown  the terminal and retry the `flutter run`, this issue may cause by hot-reload .  Because  I  copied the  hello-world code to the Editor  covered  initial project code then  double tap `R` to  hot-reload.
