### ISSUE TITLE
ERROR: Could not connect to lockdownd, error code -17

### ISSUE THREAD

**Issue by fabiom91** [flutter/website#3480]
Hi just installed flutter on android studio on my Mac and created a new default application.
At the beginning when I tried to run the app in the Android Simulator, I got several message from FileVault to allow the access to idevice, ideviceinfo etc. done that.

Now when I run the app I get the message in the title. I run the flutter doctor and this is what I get:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at
      /Users/fabiomagarelli/Developer/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fabiomagarelli/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -17

    • #0      IMobileDevice.getInfoForDevice
      (package:flutter_tools/src/ios/mac.dart:226:9)
      <asynchronous suspension>
      #1      IOSDevice.getAttachedDevices
      (package:flutter_tools/src/ios/devices.dart:190:55)
      <asynchronous suspension>
      #2      IOSDevices.pollingGetDevices
      (package:flutter_tools/src/ios/devices.dart:115:57)
      #3      PollingDeviceDiscovery.devices
      (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices
      (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate
      (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start
      (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:59:39)
      #17     _AsyncAwaitCompleter.start
      (dart:async-patch/async_patch.dart:45:6)
      #18     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:45:42)
      #19     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:615:18)
      #20     _asyncThenWrapperHelper.<anonymous closure>
      (dart:async-patch/async_patch.dart:73:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #24     Future._propagateToListeners.handleValueCallback
      (dart:async/future_impl.dart:680:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #27     Future._asyncComplete.<anonymous closure>
      (dart:async/future_impl.dart:554:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure>
      (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback
      (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage
      (dart:isolate-patch/isolate_patch.dart:175:5)


! Doctor found issues in 2 categories.
```

Any clues? .-.

**Comment by sfshaza2** [comment]
Hi, @fabiom91! Sorry for our silence, but we've been on vacation for the holidays.

I hahve no idea why you got this bug. I googled "Connected device (the doctor check crashed)", which lead me to this bug: https://github.com/flutter/flutter/issues/4159. And I followed that bug to the two bugs referenced within. It seems like some iOS folks have seen this when they didn't trust the computer from their phone. I'm not sure if this is relevant to your situation, but it's worth a look.

If you haven't figured it out, please file an issue on the Flutter SDK repo. This repo is for the website:  https://github.com/flutter/flutter/issues

Sorry I can't be more helpful and I hope you've already resolved this. If so, let us know what you discovered!

**Comment by sfshaza2** [comment]
I'll hold off closing this for a bit, until @fabiom91 can respond. But this issue should be filed on the main repo, as mentioned in the `flutter doctor` output.

**Comment by jonahwilliams** [comment]
lockdownd usually means the phone is locked or not authenticated

**Comment by mattcychen** [comment]
Hi @sfshaza2 , 
This information helps. I had the same issue as @fabiom91 does, and I found my iPhone was connected to my Mac with "Don't trust computer" chosen. After unplug my phone, simulators can run without error.

**Comment by fabiom91** [comment]
Sorry guys I had to start another project for work and I deleted flutter for now. I think the issue is that recently my iphone **always** asks me to trust my computer while before it used to cache the information. Sorry I can't give more details now since has passed some time already. Maybe @mattcychen has more to add at this point... :-/

**Comment by sfshaza2** [comment]
OK, closing.
