### ISSUE TITLE
codelabs/flutter-firebase Broken

### ISSUE THREAD

**Issue by johnwiese-ms** [flutter/website#4324]
Can't get past step 3 in the Firebase codelab (https://codelabs.developers.google.com/codelabs/flutter-firebase/#3)  using the latest cloud_firestore package.  A brand new flutter app (on Master) runs fine but as soon as you add the dependency for firestore then it refuses to build anymore.  No other changes, just add to pubspec and do a get then try to run.  I've done this on a Mac and Windows with same results.

**Comment by kwalrath** [comment]
@ditman or @filiph, can you please follow up?

**Comment by ditman** [comment]
@johnwiese-ms , have you tried completing step 7 after adding the dependency? I think another user has reported a very similar issue to this one recently.

(I'm guessing that you're attempting to run this codelab for Android?)

**Comment by johnwiese-ms** [comment]
Why would I do step 7 before step 4?  I simply did a create, hit f5 to test it, then added the package and hit f5. Which gets me through step 3 in the codelab. I have tried on PC (Android) and Mac (iOS) with the same results. On PC for Android I get errors in the debug console at least, on Mac/iOS it just sits spinning. Not sure why it is trying to use _web plugins when I have no web support enabled either?

Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :cloud_firestore_web not found. Please update settings.gradle.
D8: Cannot fit requested classes in a single dex file (# methods: 67775 > 65536)
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
The number of method references in a .dex file cannot exceed 64K.
Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.t.a(:55)
	at com.android.tools.r8.D8.run(:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
	... 34 more
Caused by: com.android.tools.r8.utils.AbortException: Error: null, Cannot fit requested classes in a single dex file (# methods: 67775 > 65536)
	at com.android.tools.r8.utils.Reporter.a(:21)
	at com.android.tools.r8.utils.Reporter.a(:7)
	at com.android.tools.r8.dex.VirtualFile.a(:33)
	at com.android.tools.r8.dex.VirtualFile$h.a(:5)
	at com.android.tools.r8.dex.ApplicationWriter.a(:13)
	at com.android.tools.r8.dex.ApplicationWriter.write(:35)
	at com.android.tools.r8.D8.d(:44)
	at com.android.tools.r8.D8.b(:1)
	at com.android.tools.r8.utils.t.a(:23)
	... 36 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
[!] The shrinker may have failed to optimize the Java bytecode.
Exited (sigterm)
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by johnwiese-ms** [comment]
Tried setting up the Firebase piece but no luck, still getting the error on Windows/Android.  I'll try iOS as well to see if they are different issues.

**Comment by sfshaza2** [comment]
Thanks for your sleuthing, @johnwiese-ms! Please keep us posted.

**Comment by aayushbisen** [comment]
Hello @johnwiese-ms 👋 

I also faced the same issue, when I was doing this codelab for the first time.

You can fix the build error you are getting by going to `android/app/build.gradle` and changing the **minSdkVersion** version from 16 to 21.

We can add this info in the codelab. 😄

**Comment by sfshaza2** [comment]
Great info, thanks!!!

**Comment by sfshaza2** [comment]
@ditman, can you fix this issue or should I?

**Comment by ditman** [comment]
@sfshaza2 I'll write something in the doc, and run it by you ASAP.

Thanks for noticing @aayushbisen!

**Comment by kwalrath** [comment]
@ditman has the codelab been updated?

**Comment by ditman** [comment]
@kwalrath not yet, but there's a fix coming. It's in the doc, and once @sfshaza2 reviews we can publish it. Apologies for the delay!

**Comment by sfshaza2** [comment]
I've published it!

**Comment by ditman** [comment]
Wowza, @sfshaza2 has just reviewed and published the change. 

Now [Step 4](https://codelabs.developers.google.com/codelabs/flutter-firebase/#3) has a note asking users to bump their `minSdkVersion` to use the firebase plugins!

I think this fixes the issue, please feel free to reopen if it doesn't!
