### ISSUE TITLE
'Linux install' page issue

### ISSUE THREAD

**Issue by timsneath** [flutter/website#5675]
Page URL: https://flutter.dev/docs/get-started/install/linux.html
Page source: https://github.com/flutter/website/tree/master/src/docs/get-started/install/linux.md

Description of issue:
Flutter's desktop support expects clang++ to be available, but this isn't mentioned in the prerequisites:

```
timsneath@tim-surface:~$ flutter doctor -v
[✓] Flutter (Channel master, 2.2.0-11.0.pre.237, on Linux, locale en_US.UTF-8)
    • Flutter version 2.2.0-11.0.pre.237 at /home/timsneath/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0f899f2b64 (75 minutes ago), 2021-04-22 15:01:49 -0700
    • Engine revision 9ea763842e
    • Dart version 2.14.0 (build 2.14.0-18.0.dev)

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[☠] Linux toolchain - develop for Linux desktop (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us
      know about this issue at https://github.com/flutter/flutter/issues.
    ✗ ProcessException: Failed to find "clang++" in the search path.
        Command: clang++ 
    • #0      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:89:7)
      #1      ErrorHandlingProcessManager.run.<anonymous closure>
      (package:flutter_tools/src/base/error_handling_io.dart:642:24)
      #2      _run (package:flutter_tools/src/base/error_handling_io.dart:544:20)
      #3      ErrorHandlingProcessManager.run (package:flutter_tools/src/base/error_handling_io.dart:641:12)
      #4      LinuxDoctorValidator._getBinaryVersion (package:flutter_tools/src/linux/linux_doctor.dart:166:38)
      #5      LinuxDoctorValidator.validate (package:flutter_tools/src/linux/linux_doctor.dart:68:25)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #8      _rootRun (dart:async/zone.dart:1354:13)
      #9      _CustomZone.run (dart:async/zone.dart:1258:19)
      #10     _runZoned (dart:async/zone.dart:1789:10)
      #11     runZonedGuarded (dart:async/zone.dart:1777:12)
      #12     runZoned (dart:async/zone.dart:1708:12)
      #13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:200:9)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:304:47)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:47)
      #17     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1208:12)
      <asynchronous suspension>
      #18     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1059:27)
      <asynchronous suspension>
      #19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #20     CommandRunner.runCommand (package:args/command_runner.dart:196:13)
      <asynchronous suspension>
      #21     FlutterCommandRunner.runCommand.<anonymous closure>
      (package:flutter_tools/src/runner/flutter_command_runner.dart:284:9)
      <asynchronous suspension>
      #22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:232:5)
      <asynchronous suspension>
      #24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #26     main (package:flutter_tools/executable.dart:91:3)
      <asynchronous suspension>


[✗] Flutter IDE Support (No supported IDEs installed)
    • IntelliJ - https://www.jetbrains.com/idea/
    • Android Studio - https://developer.android.com/studio/
    • VS Code - https://code.visualstudio.com/

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Linux

! Doctor found issues in 3 categories.
timsneath@tim-surface:~$ 
```

**Comment by piedcipher** [comment]
It is mentioned here: https://flutter.dev/desktop#additional-linux-requirements

**Comment by piedcipher** [comment]
https://flutter.dev/docs/get-started/install/linux.html is for installing Flutter SDK for Linux users, not for flutter desktop app development in Linux.

**Comment by timsneath** [comment]
Just for clarity, we see Flutter as a platform for desktop, web _and_ mobile. Our goal is that instructions should be applicable for all three (that is, neither desktop nor web are secondary platforms to mobile -- they're all just as much targets for Flutter). It's great that some of this is in the desktop page, but we expect many Linux developers to install Flutter for Linux development, so we will need to include some of this (or at the very least, prominent links) in the main page.
