### ISSUE TITLE
[PAGE ISSUE]: 'macOS install'

### ISSUE THREAD

**Issue by venugoudamaragani** [flutter/website#6285]
### Page URL

https://flutter.dev/docs/get-started/install/macos/

### Page source

https://github.com/flutter/website/tree/main/src/docs/get-started/install/macos.md

### Describe the problem

unable to run flutter and flutter doctor
```
Unhandled exception:
Exception: Flutter failed to create a directory at "/Users/venugoudamaragani/.config/flutter".
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
#1      _throwFileSystemException (package:flutter_tools/src/base/error_handling_io.dart:813:3)
#2      _handlePosixException (package:flutter_tools/src/base/error_handling_io.dart:761:3)
#3      _runSync (package:flutter_tools/src/base/error_handling_io.dart:607:7)
#4      ErrorHandlingDirectory.createSync (package:flutter_tools/src/base/error_handling_io.dart:432:12)
#5      new Config._common (package:flutter_tools/src/base/config.dart:77:17)
#6      new Config (package:flutter_tools/src/base/config.dart:37:19)
#7      new _DefaultPersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:69:18)
#8      new PersistentToolState (package:flutter_tools/src/persistent_tool_state.dart:21:9)
#9      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:302:34)
#10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:42)
#11     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:314:23)
#12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#13     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#14     PersistentToolState.instance (package:flutter_tools/src/persistent_tool_state.dart:35:55)
#15     persistentToolState (package:flutter_tools/src/globals_null_migrated.dart:63:69)
#16     _defaultBotDetector (package:flutter_tools/src/globals_null_migrated.dart:69:24)
#17     _defaultBotDetector (package:flutter_tools/src/globals_null_migrated.dart)
#18     botDetector (package:flutter_tools/src/globals_null_migrated.dart:65:62)
#19     isRunningOnBot (package:flutter_tools/src/globals_null_migrated.dart:75:36)
#20     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:81:34)
#21     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:80:28)
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
#24     _rootRun (dart:async/zone.dart:1428:13)
#25     _CustomZone.run (dart:async/zone.dart:1328:19)
#26     _runZoned (dart:async/zone.dart:1863:10)
#27     runZoned (dart:async/zone.dart:1785:10)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
#29     runInContext (package:flutter_tools/src/context_runner.dart:85:18)
#30     run (package:flutter_tools/runner.dart:45:10)
#31     main (package:flutter_tools/executable.dart:92:9)
#32     main (file:///opt/s/w/ir/x/w/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:10:3)
#33     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by darshankawar** [comment]
@venugoudamaragani 
As the error indicates:

`Exception: Flutter failed to create a directory at "/Users/venugoudamaragani/.config/flutter".
Please ensure that the SDK and/or project is installed in a location that has read/write permissions for the current user.`

The location of your SDK doesn't have the right permissions. Make sure the directory has read/write permissions, if not change location to the directory that has these permissions
Closing, as this isn't an issue with website / page itself. If you disagree, please write in the comments and I will reopen it.
Thank you
