### ISSUE TITLE
Unable to bring up site for local development

### ISSUE THREAD

**Issue by guidezpl** [flutter/website#6440]
### Describe the problem

After running `make setup` `make up` fails with the following error. I'm on macOS monterey if that matters

```
make up                   
docker-compose up site
[+] Running 1/0
 ⠿ Container website-site-1  Created                                               0.0s
Attaching to website-site-1
website-site-1  | bundle exec jekyll serve \
website-site-1  |       --host 0.0.0.0 \
website-site-1  |       --port 4002 \
website-site-1  |       --config _config.yml,_config_dev.yml \
website-site-1  |       --livereload \
website-site-1  |       --incremental \
website-site-1  |       --trace
website-site-1  | Configuration file: /app/_config.yml
website-site-1  | Configuration file: /app/_config_dev.yml
website-site-1  |   Dependency Error: Yikes! It looks like you don't have /app/src/_plugins/breadcrumb.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the /app/src/_plugins/breadcrumb.rb gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- /app/src/_plugins/breadcrumb.rb' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
website-site-1  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
website-site-1  | /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/external.rb:73:in `rescue in block in require_with_graceful_fail': /app/src/_plugins/breadcrumb.rb (Jekyll::Errors::MissingDependencyException)
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/external.rb:58:in `block in require_with_graceful_fail'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/external.rb:57:in `each'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:89:in `block in require_plugin_files'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:87:in `each'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:87:in `require_plugin_files'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/site.rb:131:in `setup'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/site.rb:36:in `initialize'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:30:in `new'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:30:in `process'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
website-site-1  |       from /usr/local/bundle/bin/jekyll:23:in `load'
website-site-1  |       from /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:58:in `load'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:58:in `kernel_load'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:23:in `run'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:478:in `exec'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:31:in `dispatch'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:25:in `start'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/exe/bundle:49:in `block in <top (required)>'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/exe/bundle:37:in `<top (required)>'
website-site-1  |       from /usr/local/bundle/bin/bundle:23:in `load'
website-site-1  |       from /usr/local/bundle/bin/bundle:23:in `<main>'
website-site-1  | /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/external.rb:60:in `require': cannot load such file -- /app/src/_plugins/breadcrumb.rb (LoadError)
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/external.rb:60:in `block in require_with_graceful_fail'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/external.rb:57:in `each'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/external.rb:57:in `require_with_graceful_fail'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:89:in `block in require_plugin_files'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:87:in `each'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:87:in `require_plugin_files'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/plugin_manager.rb:21:in `conscientious_require'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/site.rb:131:in `setup'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/site.rb:36:in `initialize'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:30:in `new'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:30:in `process'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
website-site-1  |       from /usr/local/bundle/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
website-site-1  |       from /usr/local/bundle/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
website-site-1  |       from /usr/local/bundle/bin/jekyll:23:in `load'
website-site-1  |       from /usr/local/bundle/bin/jekyll:23:in `<top (required)>'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:58:in `load'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:58:in `kernel_load'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:23:in `run'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:478:in `exec'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:31:in `dispatch'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:25:in `start'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/exe/bundle:49:in `block in <top (required)>'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
website-site-1  |       from /usr/local/bundle/gems/bundler-2.2.30/exe/bundle:37:in `<top (required)>'
website-site-1  |       from /usr/local/bundle/bin/bundle:23:in `load'
website-site-1  |       from /usr/local/bundle/bin/bundle:23:in `<main>'
website-site-1  | make: *** [Makefile:61: serve] Error 1
website-site-1 exited with code 2
```

**Comment by guidezpl** [comment]
I tried `make reinstall`, after which I get a slightly different error. Any ideas @hrishikesh-kadam?
```
rm -f Gemfile.lock
bundle install --redownload
Ignoring ffi-1.15.4 because its extensions are not built. Try: gem pristine ffi --version 1.15.4
Ignoring iStats-1.6.1 because its extensions are not built. Try: gem pristine iStats --version 1.6.1
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Installing concurrent-ruby 1.1.9
Installing zeitwerk 2.5.1
Installing public_suffix 4.0.6
Using bundler 2.2.27
Installing rexml 3.2.5
Fetching eventmachine 1.2.7
Fetching http_parser.rb 0.6.0
Fetching colorator 1.1.0
Fetching minitest 5.14.4
Fetching rb-fsevent 0.11.0
Fetching forwardable-extended 2.6.0
Fetching ffi 1.15.4
Fetching liquid 4.0.3
Installing colorator 1.1.0
Installing forwardable-extended 2.6.0
Fetching mercenary 0.4.0
Installing rb-fsevent 0.11.0
Installing minitest 5.14.4
Installing liquid 4.0.3
Installing http_parser.rb 0.6.0 with native extensions
Fetching rouge 3.26.1
Fetching safe_yaml 1.0.5
Installing eventmachine 1.2.7 with native extensions
Installing mercenary 0.4.0
Installing ffi 1.15.4 with native extensions
Installing safe_yaml 1.0.5
Fetching unicode-display_width 1.8.0
Fetching racc 1.6.0
Fetching webrick 1.7.0
Fetching extras 0.3.0
Installing rouge 3.26.1
Installing unicode-display_width 1.8.0
Installing racc 1.6.0 with native extensions
Installing webrick 1.7.0
Installing extras 0.3.0
Fetching pathutil 0.16.2
Installing addressable 2.8.0
Fetching terminal-table 2.0.0
Installing pathutil 0.16.2
Fetching kramdown 2.3.1
Installing terminal-table 2.0.0
Installing kramdown 2.3.1
Fetching liquid-tag-parser 2.0.2
Installing liquid-tag-parser 2.0.2
Installing tzinfo 2.0.4
Fetching i18n 1.8.11
Installing i18n 1.8.11
Installing activesupport 6.1.4.1
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Fetching nokogiri 1.12.5 (x86_64-darwin)
Fetching nokogiri 1.12.5 (arm64-darwin)
Installing nokogiri 1.12.5 (x86_64-darwin)
Installing nokogiri 1.12.5 (arm64-darwin)
Fetching sassc 2.4.0
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching listen 3.7.0
Installing sassc 2.4.0 with native extensions
Installing listen 3.7.0
Fetching jekyll-watch 2.2.1
Installing jekyll-watch 2.2.1
Fetching em-websocket 0.5.2
Installing em-websocket 0.5.2
Fetching jekyll-sass-converter 2.1.0
Installing jekyll-sass-converter 2.1.0
Fetching jekyll 4.2.0
Installing jekyll 4.2.0
Fetching jekyll-toc 0.17.1
Installing jekyll-toc 0.17.1
Bundle complete! 5 Gemfile dependencies, 39 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.



Imake up
docker-compose up site
[+] Running 1/0
 ⠿ Container website-site-1  Created                                                 0.0s
Attaching to website-site-1
website-site-1  | bundle exec jekyll serve \
website-site-1  | 	--host 0.0.0.0 \
website-site-1  | 	--port 4002 \
website-site-1  | 	--config _config.yml,_config_dev.yml \
website-site-1  | 	--livereload \
website-site-1  | 	--incremental \
website-site-1  | 	--trace
website-site-1  | bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
website-site-1  | /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/definition.rb:501:in `materialize': Could not find i18n-1.8.11, zeitwerk-2.5.1, racc-1.6.0 in any of the sources (Bundler::GemNotFound)
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/definition.rb:239:in `specs_for'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/runtime.rb:18:in `setup'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler.rb:150:in `setup'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/setup.rb:20:in `block in <top (required)>'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/ui/shell.rb:136:in `with_level'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/ui/shell.rb:88:in `silence'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/setup.rb:20:in `<top (required)>'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:56:in `require_relative'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:56:in `kernel_load'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:23:in `run'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:478:in `exec'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:31:in `dispatch'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/cli.rb:25:in `start'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/exe/bundle:49:in `block in <top (required)>'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
website-site-1  | 	from /usr/local/bundle/gems/bundler-2.2.30/exe/bundle:37:in `<top (required)>'
website-site-1  | 	from /usr/local/bundle/bin/bundle:23:in `load'
website-site-1  | 	from /usr/local/bundle/bin/bundle:23:in `<main>'
website-site-1  | make: *** [Makefile:61: serve] Error 1
website-site-1 exited with code 2
```

**Comment by hrishikesh-kadam** [comment]
```
website-site-1  |   Dependency Error: Yikes! It looks like you don't have /app/src/_plugins/breadcrumb.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the /app/src/_plugins/breadcrumb.rb gem in your Gemfile as well. The full error message from Ruby is: 'cannot load such file -- /app/src/_plugins/breadcrumb.rb' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
```
@guidezpl Have you cloned submodules also?
Reference - https://github.com/flutter/website#2-clone-this-repo-and-its-submodules

**Comment by guidezpl** [comment]
Yes, but it looks like they got in a weird state. Did the natural thing–blasted the repo and started fresh–and it works!
