### ISSUE TITLE
Unable to run Flutter Firebase codelab

### ISSUE THREAD

**Issue by juicemia** [flutter/website#8271]
### Page URL

https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#0

### Describe the problem

I first went to open this issue with Cocoapods but in their issue template they say they don't help with Flutter projects using Cocoapods and that they'll automatically close any issues that have anything to do with it. I then tried opening this issue in the [codelabs](https://github.com/flutter/codelabs) repo but it looks like issues are disabled on that repo because the "Issues" tab is missing. After that I tried [going directly to the Flutterfire repo](https://github.com/firebase/flutterfire/issues/10455), and they referred me here.

I'm unable to get through the Flutter code lab for Firebase. When I try running the app on the simulator using `flutter run` (this is in [step 4](https://firebase.google.com/codelabs/firebase-auth-in-flutter-apps#3)) I get an error running `pod install`. I can successfully run the getting started app from the [MacOS installation docs](https://docs.flutter.dev/get-started/install/macos).

This is the error I'm getting from Cocoapods:

```
JSON::ParserError - unexpected token at '"src/core/ext/upb-generated/envoy/config/endpoint/v3/endpoint_components.'
2
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:748:in `from_string'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/specification.rb:722:in `from_file'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source.rb:188:in `specification'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver/lazy_specification.rb:37:in `specification'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/3.2.0/delegate.rb:348:in `block in delegating_block'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/3.2.0/delegate.rb:349:in `block in delegating_block'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:178:in `dependencies_for'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `reverse_each'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:808:in `group_possibilities'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:779:in `possibilities_for_requirement'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Users/juice/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/Users/juice/.rbenv/versions/3.2.1/bin/pod:25:in `load'
/Users/juice/.rbenv/versions/3.2.1/bin/pod:25:in `<main>'
```

### Additional context

I honestly don't know where else to open this issue.

**Comment by danagbemava-nc** [comment]
Hi @juicemia, I run through the codelab myself and I did not get an issue with `pod install` so this is likely an issue with your local pod setup. 
Can you try running the command in https://github.com/CocoaPods/CocoaPods/issues/9578#issuecomment-746809260 to 
see if it helps?
[The reason the default flutter app is able to run is because it does not use any plugins so there's no Podfile and thus no need to run `pod install`]

**Comment by juicemia** [comment]
@danagbemava-nc thanks for the suggestion. I ended up going a bit farther than that. I completely erased my whole setup, including getting rid of `rbenv` entirely and removing the `cocoapods` gems I had installed with my system ruby. I then reinstalled everything following the getting started documentation for flutter, and now it's working.
